### ISSUE TITLE
nitaAllCombinationWRMillisecondsを追加して全カスタムのWRを確認できるようにする

### ISSUE THREAD

**Issue by moeyashi** [moeyashi/discord-mk8d-nita-record#37]

**Comment by hitonohazi** [comment]
よろしくお願いします！
とりあえずコードの共有ってどうすれば良いんですかね…？

**Comment by moeyashi** [comment]
@hitonohazi もしGitやってみたい、みたいなモチベがあれば、ForkしてPull Requestを送るという方法があります
https://qiita.com/wataryooou/items/8dce6b6d5f54ab2cef04

とくになければ、このコメントでtrack.jsのコードを張り付けてもらってもOKです！

**Comment by hitonohazi** [comment]
@moeyashi 
Qiitaの記事を参考にPull Requestを送ってみたのですが、問題なさそうでしょうか…？

**Comment by moeyashi** [comment]
@hitonohazi マージさせて頂きました！ありがとうございます！！
